@startuml
rectangle connector_producer_activeMqSourceConnector_0
queue incoming.activemq
rectangle _confluent_ksql_default_query_CSAS_INCOMING_OP_MSGS_7_ad639a0b_af7f_4fc8_82dc_8074f5c6b0ce_StreamThread_1_producer
queue INCOMING_OP_MSGS
rectangle _confluent_ksql_default_query_CSAS_INCOMING_OP_MSGS_7
rectangle _confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5
queue STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN
rectangle connect_audit_es_sink
queue RAW_VOIP_INSTRUCTIONS
rectangle connect_audit_es_sink
queue modify.op.msgs
rectangle connect_audit_es_sink
queue AUDIT
rectangle _confluent_ksql_default_query_CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1
rectangle _confluent_ksql_default_query_CSAS_RAW_VOIP_INSTRUCTIONS_0
rectangle _confluent_ksql_default_query_CSAS_RAW_VOIP_INSTRUCTIONS_0_d11c8416_0571_4569_b893_252d1cf6a4d9_StreamThread_3_producer
rectangle _confluent_ksql_default_query_CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1_178addac_b4c0_48fa_b591_8d59cca7b6cc_StreamThread_1_producer
queue REKEYED_RAW_VOIP_INSTRUCTIONS
rectangle _confluent_ksql_default_query_CSAS_AUDIT_8_31162899_1403_49bf_bc2a_6d4349254f1f_StreamThread_3_producer
rectangle _confluent_ksql_default_query_CSAS_AUDIT_8
rectangle _confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3_87c3a52c_adf2_4c4c_af61_a9d4745cb0c4_StreamThread_3_producer
rectangle _confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3
rectangle _confluent_ksql_default_query_InsertQuery_9_f220a050_796d_4a6f_8e57_40ebe6a445cc_StreamThread_3_producer
rectangle _confluent_ksql_default_query_InsertQuery_9
rectangle _confluent_ksql_default_query_CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6_40382c9c_5dd5_4c18_b748_efe4e5e3e965_StreamThread_1_producer
queue SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
rectangle _confluent_ksql_default_query_CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6
queue STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
rectangle _confluent_ksql_default_query_InsertQuery_10_1a2759fb_ce0f_4608_99fe_4f8b2ed25d21_StreamThread_3_producer
rectangle _confluent_ksql_default_query_InsertQuery_10
rectangle _confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5_73185a9f_1ed6_4033_8507_1795e3368c4c_StreamThread_1_producer
rectangle connect_AMQSinkConnector
queue switch.modification.instructions
rectangle connect_audit_es_sink
connector_producer_activeMqSourceConnector_0->incoming.activemq
_confluent_ksql_default_query_CSAS_INCOMING_OP_MSGS_7_ad639a0b_af7f_4fc8_82dc_8074f5c6b0ce_StreamThread_1_producer->INCOMING_OP_MSGS
_confluent_ksql_default_query_CSAS_INCOMING_OP_MSGS_7->incoming.activemq
_confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5->STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN
connect_audit_es_sink->RAW_VOIP_INSTRUCTIONS
connect_audit_es_sink->modify.op.msgs
connect_audit_es_sink->AUDIT
_confluent_ksql_default_query_CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1->RAW_VOIP_INSTRUCTIONS
_confluent_ksql_default_query_CSAS_RAW_VOIP_INSTRUCTIONS_0->modify.op.msgs
_confluent_ksql_default_query_CSAS_RAW_VOIP_INSTRUCTIONS_0_d11c8416_0571_4569_b893_252d1cf6a4d9_StreamThread_3_producer->RAW_VOIP_INSTRUCTIONS
_confluent_ksql_default_query_CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1_178addac_b4c0_48fa_b591_8d59cca7b6cc_StreamThread_1_producer->REKEYED_RAW_VOIP_INSTRUCTIONS
_confluent_ksql_default_query_CSAS_AUDIT_8_31162899_1403_49bf_bc2a_6d4349254f1f_StreamThread_3_producer->AUDIT
_confluent_ksql_default_query_CSAS_AUDIT_8->modify.op.msgs
_confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3_87c3a52c_adf2_4c4c_af61_a9d4745cb0c4_StreamThread_3_producer->STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN
_confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3->REKEYED_RAW_VOIP_INSTRUCTIONS
_confluent_ksql_default_query_InsertQuery_9_f220a050_796d_4a6f_8e57_40ebe6a445cc_StreamThread_3_producer->AUDIT
_confluent_ksql_default_query_InsertQuery_9->RAW_VOIP_INSTRUCTIONS
_confluent_ksql_default_query_CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6_40382c9c_5dd5_4c18_b748_efe4e5e3e965_StreamThread_1_producer->SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
_confluent_ksql_default_query_CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6->STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
_confluent_ksql_default_query_InsertQuery_10_1a2759fb_ce0f_4608_99fe_4f8b2ed25d21_StreamThread_3_producer->AUDIT
_confluent_ksql_default_query_InsertQuery_10->SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
_confluent_ksql_default_query_CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5_73185a9f_1ed6_4033_8507_1795e3368c4c_StreamThread_1_producer->STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
connect_AMQSinkConnector->switch.modification.instructions
connect_audit_es_sink->SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
@enduml
