@startuml
rectangle connector_producer_activeMqSourceConnector_0
queue incoming.activemq
rectangle CSAS_INCOMING_OP_MSGS_7
queue INCOMING_OP_MSGS
rectangle CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5
queue STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN
rectangle connect_audit_es_sink
queue RAW_VOIP_INSTRUCTIONS
queue modify.op.msgs
queue AUDIT
rectangle CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1
rectangle CSAS_RAW_VOIP_INSTRUCTIONS_0
queue REKEYED_RAW_VOIP_INSTRUCTIONS
rectangle CSAS_AUDIT_8
rectangle CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3
rectangle InsertQuery_9
rectangle CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6
queue SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
queue STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
rectangle InsertQuery_10
rectangle connect_AMQSinkConnector
queue switch.modification.instructions
connector_producer_activeMqSourceConnector_0->incoming.activemq
CSAS_INCOMING_OP_MSGS_7->INCOMING_OP_MSGS
incoming.activemq<-CSAS_INCOMING_OP_MSGS_7
STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN<-CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5
RAW_VOIP_INSTRUCTIONS<-connect_audit_es_sink
modify.op.msgs<-connect_audit_es_sink
AUDIT<-connect_audit_es_sink
RAW_VOIP_INSTRUCTIONS<-CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1
modify.op.msgs<-CSAS_RAW_VOIP_INSTRUCTIONS_0
CSAS_RAW_VOIP_INSTRUCTIONS_0->RAW_VOIP_INSTRUCTIONS
CSAS_REKEYED_RAW_VOIP_INSTRUCTIONS_1->REKEYED_RAW_VOIP_INSTRUCTIONS
CSAS_AUDIT_8->AUDIT
modify.op.msgs<-CSAS_AUDIT_8
CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3->STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN
REKEYED_RAW_VOIP_INSTRUCTIONS<-CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_DN_3
InsertQuery_9->AUDIT
RAW_VOIP_INSTRUCTIONS<-InsertQuery_9
CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6->SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID<-CSAS_SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_6
InsertQuery_10->AUDIT
SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID<-InsertQuery_10
CSAS_STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID_5->STREAM_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID
switch.modification.instructions<-connect_AMQSinkConnector
SINK_MODIFY_VOIP_INSTRUCTIONS_WITH_SWITCH_ID<-connect_audit_es_sink
@enduml